### PR TITLE
Disabiguate fields in findByIngredient query

### PR DESCRIPTION
**Pull request by ilveroluca**
Seems to address issue #67

### CODE REVIEW

**Review by nazgul26 — APPROVED** [review]
Tested locally and does not introduce any problems.

**Comment by nazgul26** [comment]
I could not reproduce the issue reported. Looks like this could help and does not introduce any issues. Thanks!

**Comment by ilveroluca** [comment]
I'm running on PostgreSQL. Maybe that explains the different behaviour?

**Comment by nazgul26** [comment]
Most likely.  While cakePHP does try to support multiple databases without having to code differently that does not always work perfectly.

**Pull request merged**
